/* eslint-disable prettier/prettier */

export const SET_MODIFIED_PARAMETER_LIST = 'SET_MODIFIED_PARAMETER_LIST';
export const SET_EXPERION_MODIFICATION_FORMULA_LIST =
  'SET_EXPERION_MODIFICATION_FORMULA_LIST';
