export const UPDATE_PENDING_APPROVAL_ITEMS = 'UPDATE_PENDING_APPROVAL_ITEMS';
export const UPDATE_FORMULA_SET = 'UPDATE_FORMULA_SET';
export const UPDATE_FORMULA = 'UPDATE_FORMULA';
export const UPDATE_FORMULA_SET_COMMENTS = 'UPDATE_FORMULA_SET_COMMENTS';
export const UPDATE_FORMULA_COMMENTS = 'UPDATE_FORMULA_COMMENTS';
export const UPDATE_PENDING_CAMPAIGN_LIST = 'UPDATE_PENDING_CAMPAIGN_LIST';
