export const SET_FORMULASETS = 'SET_FORMULASETS';
export const DELELE_FORMULASET = 'DELELE_FORMULASET';
export const REFRESH_FOR_EXPERION_MODIFICATION = 'DELELE_FORMULASET';
export const UPDATE_EXPERION_CHANGES_MR_ITEMS =
  'UPDATE_EXPERION_CHANGES_MR_ITEMS';
export const UPDATE_SIGNALR_CONNECTION_STATUS =
  'UPDATE_SIGNALR_CONNECTION_STATUS';
export const GET_APP_SETTINGS_STATUS = 'GET_APP_SETTINGS_STATUS';
export const IS_EXPERION_CHANGE_ALLOWED = 'IS_EXPERION_CHANGE_ALLOWED';
